apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: traefik
data:
  traefik.yaml: |
    api:
      dashboard: true
      insecure: true
    providers:
      redis:
        endpoints: "192.168.3.201:6379"
        rootKey: "traefik"
        password: "Datapipeline123"
    accessLog: {}
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"
    log:
      level: DEBUG

